blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord Community
    url: https://discord.gg/C87Pvq3
    about: Join the Official Homebridge Discord community and ask in the ui channel.