name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version / Tag (x.x.x):'
        required: true
      create_release:
        type: boolean
        default: true
        description: Create release?
      prerelease:
        type: boolean
        default: true
        description: Pre-release?

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        if: github.event.inputs.create_release == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          prerelease: ${{ github.event.inputs.prerelease }}
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install package
        run: |
          export npm_config_prefix=$(pwd)/package
          npm install -g homebridge-config-ui-x@${{ github.event.inputs.version }}
      - name: Create Bundle
        run: |
          tar -C $(pwd)/package -czvf homebridge-config-ui-x-${{ github.event.inputs.version }}.tar.gz .
          ls -la 
          pwd
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'homebridge-config-ui-x-${{ github.event.inputs.version }}.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.event.inputs.version }}

