name: Test

on: [
  pull_request,
  push
]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x, 15.x]
        include:
          - os: macos-latest
            node: 14.x
          - os: windows-latest
            node: 14.x

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build:server
      - run: npm run lint:server
      - run: npm run test:e2e

      # remove dev deps
      - run: npm clean-install --production

      # test hb-service
      - run: node dist/bin/hb-service.js -v
      - if: runner.os == 'Linux'
        name: 'Run hb-service install (Linux)'
        run: |
          sudo npm link
          sudo npm install -g homebridge
          sudo hb-service install --user homebridge
          sleep 30
      - if: runner.os == 'macOS'
        name: 'Run hb-service install (macOS)'
        run: |
          sudo npm link
          sudo npm install -g homebridge
          sudo hb-service install
          sleep 30
      - if: runner.os == 'Windows'
        name: 'Run hb-service install (Windows)'
        run: |
          npm link
          npm install -g homebridge
          hb-service install
          Start-Sleep -s 30
      - name: 'Test hb-service install'
        run: node dist/bin/hb-service.js status --port 8581
        